site_name: SHL - Sophia Hack Lab

# Doc: https://squidfunk.github.io/mkdocs-material/setup/
theme:
  name: material
  logo: https://0xdc.me/mkdocs-example/img/shl-logo.png
  favicon: https://0xdc.me/mkdocs-example/img/shl-logo.png

  palette:
    primary: black
    accent: green

  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - 'index.md'
  - 'projects.md'
  - 'members.md'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SophiaHackLab

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/sophia-hack-lab/

    - icon: fontawesome/brands/instagram
      link: https://instagram.com/shl_sophiahacklab

# Doc: https://squidfunk.github.io/mkdocs-material/plugins/
plugins:
  - optimize
